### ISSUE TITLE
unexpected events.length == 0 

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-cli#24]
# Description
In certain situations, events.length may unexpectedly become 0.
Please reproduce the following steps:

### 1. Init zkgraph@alpha
```
npm init zkgraph@alpha
```

zkgraph.yaml which dataSources is mainnet event as below:
```
specVersion: 0.0.2
apiVersion: 0.0.2
name: eg_event
description: "This demo zkGraph shows 3 ways to access / filter out source events."
repository: https://github.com/hyperoracle/zkgraph
dataSources:
  - kind: ethereum
    network: mainnet
    event:
      - address: '0xdac17f958d2ee523a2206206994597c13d831ec7'
        events: 
          - "Transfer(address,address,uint256)"

mapping:
  language: wasm/assemblyscript
  file: ./mapping.ts
  handler: handleBlocks

dataDestinations:
  - kind: ethereum
    network: sepolia
    address: "0x0000000000000000000000000000000000000001"

```
### 2. code mapping.ts
console.log the events.length as a string:
```
//@ts-ignore
import { Bytes, Block, Event } from "@hyperoracle/zkgraph-lib";

export function handleBlocks(blocks: Block[]): Bytes {

  // #1 can access all (matched) events of the latest block
  let events: Event[] = blocks[0].events;

  console.log(events.length.toString());

  return Bytes.fromI32(1);
}
```

### 3. compile and execute

```
 npm run compile && npm run exec -- 18518315
```
<img width="527" alt="image" src="https://github.com/hyperoracle/zkgraph-cli/assets/103174898/1cba636a-a2d4-47d8-928b-475b642ab342">
