### ISSUE TITLE
unexpected events.length == 0 when event.data too huge

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-cli#32]
unexpected events.length == 0 when event.data too huge

### Env
- zkgraph-lib: 1.0.1
- zkgraph-cli: 1.0.0-alpha.0

### reproduce
1. `npm init zkgraph@latest`
2. Initialize the zkgraph project according to the guidelines.
3. modify package.json with specific version of zkgraph-lib and zkgraph-cli
4. modify zkgraph.config.ts with developing compiler server
```typescript
import { UserConfig } from "@hyperoracle/zkgraph-cli";

export default {
  UserPrivateKey:
    "YOUR_PRIVATE_KEY",
  PinataJWT: "",
  ZkwasmProviderUrl: "https://rpc.zkwasmhub.com:8090",
  CompilerServerEndpoint: "http://compiler.dev.hyperoracle.io/compile",
} as UserConfig;
```

5. modify `src/mapping.ts` into below code:
```typescript
//@ts-ignore
import { Bytes, Block } from "@hyperoracle/zkgraph-lib";

export function handleBlocks(blocks: Block[]): Bytes {
  const events = blocks[0].events;
  console.log(events.length.toString());
  return Bytes.fromUTF8("Hello zkGraph!");
}
```

6. modify `src/zkgraph.yaml` into following code:
```yaml
specVersion: 0.0.2
apiVersion: 0.0.2
name: eg_hello
description: "This demo zkGraph always set a ascii string as the output state. "
repository: https://github.com/hyperoracle/zkgraph
dataSources:
  - kind: ethereum
    network: mainnet
    event:
      - address: '0xa0e22e94433779c859dddeeaf8c6f15b16b662f4'
        events: 
          - '0x665fba0baf3dc33e9943340197893ac16f56482c2defb8de60f944987fee451c'

mapping:
  language: wasm/assemblyscript
  file: ./mapping.ts
  handler: handleBlocks

dataDestinations:
  - kind: ethereum
    network: sepolia
    address: "0x0000000000000000000000000000000000000001"
```

7. run command `npm run compile && npm run exec -- 18137200`
8. The events.length as 0 in Logs.

![image](https://github.com/hyperoracle/zkgraph-cli/assets/103174898/cc07a42d-e7af-4a1d-9205-13d4d29f680c)

**Comment by LiRiu** [comment]
Correction:
The reason for events.length == 0 may not be data too large. The same exception occurred when trying to process smaller event.data.
New bug reproduction src/zkgraph.yaml is:
```
specVersion: 0.0.2
apiVersion: 0.0.2
name: ethscription
description: "This zkgraph is image collection of ethscription."
repository: https://github.com/liriu/zkEthscription
dataSources:
  - kind: ethereum
    network: sepolia
    event:
      - address: '0xfA002dC692D045aFde265d5eaC09d012C1AF50E8'
        events: 
          - '0x665fba0baf3dc33e9943340197893ac16f56482c2defb8de60f944987fee451c'

mapping:
  language: wasm/assemblyscript
  file: ./mapping.ts
  handler: handleBlocks

dataDestinations:
  - kind: ethereum
    network: sepolia
    address: "0x0000000000000000000000000000000000000001"
```

please run command: `npm run compile && npm run exec -- 4940503`
