### ISSUE TITLE
prove panic by unknown error

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-cli#33]
It seems that the prove API is temporarily unable to function properly.
Can be reproduced with any existing zkgraph.

also can be reproduced with following steps:
1. `npm init zkgraph@latest`
2. Follow the instructions to complete the initialization.
3. modify zkgraph.config.ts with `CompilerServerEndpoint: "http://compiler.dev.hyperoracle.io/compile"`
4. modify mapping.ts and zkgraph.yaml as following code:
mapping.ts

```typescript
//@ts-ignore
import { Bytes, Account, Block, BigInt } from "@hyperoracle/zkgraph-lib";

let addr = Bytes.fromHexString("0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8");
let key = Bytes.fromHexString(
  "0x0000000000000000000000000000000000000000000000000000000000000000"
);

function calculatePrice(sqrtPrice: BigInt): BigInt {
  const e12 = BigInt.fromI32(10).pow(12);
  const n = sqrtPrice.div(BigInt.fromI32(2).pow(96));
  return e12.div(n.pow(2));
}

export function handleBlocks(blocks: Block[]): Bytes {
  let acct: Account = blocks[0].account(addr);
  let value: Bytes = acct.storage(key);

  let priceSqrtBytesX96: Bytes = value.slice(11, 31);
  const priceSqrt: BigInt = BigInt.fromBytes(priceSqrtBytesX96);
  const price = calculatePrice(priceSqrt);

  return Bytes.fromHexString(price.toHex());
}

```

zkgraph.yaml
```yaml
specVersion: 0.0.2
apiVersion: 0.0.2
name: eg_storage
description: "calculate uniswap v3 WETH-USDC price with storage interface"
repository: https://github.com/hyperoracle/zkgraph
dataSources:
  - kind: ethereum
    network: mainnet
    storage:
      - address: '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'
        slots: 
          - 0

mapping:
  language: wasm/assemblyscript
  file: ./mapping.ts
  handler: handleBlocks

dataDestinations:
  - kind: ethereum
    network: sepolia
    address: "0x0000000000000000000000000000000000000001"
```

5. run command `npm run compile && npm run setup` ( maybe already setup )
6. run command `npm run prove -- 18827736 08cc --prove`

At this time, an HTTPS error without catch will cause a panic.
![image](https://github.com/hyperoracle/zkgraph-cli/assets/103174898/2f507b72-0475-4b73-9e13-65bf2f5dc02e)
