### ISSUE TITLE
When slot.Key is equal to 0, the prove will fail.

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-cli#37]
When slot.Key is equal to 0, the prove will fail.

### Env
- zkgraph-lib: v1.0.1
- zkgraph-cli: v1.0.0
- zkgraph-api: v1.0.3
- compiler: `http://compiler.hyperoracle.io/compile`

### Reproduce
1. npm init zkgraph@latest
2. Follow the instructions to create a project of storage type.
3. modify zkgraph.yaml as follow:
```yaml
specVersion: 0.0.2
apiVersion: 0.0.2
name: eg_storage
description: "This demo zkGraph shows 2 ways to access a slot value."
repository: https://github.com/hyperoracle/zkgraph
dataSources:
  - kind: ethereum
    network: mainnet
    storage:
      - address: '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'
        slots: 
          - 1

mapping:
  language: wasm/assemblyscript
  file: ./mapping.ts
  handler: handleBlocks

dataDestinations:
  - kind: ethereum
    network: sepolia
    address: "0x0000000000000000000000000000000000000001"
```
4. modify mapping.ts as follow:
```
//@ts-ignore
import { Bytes, Account, Block, BigInt } from "@hyperoracle/zkgraph-lib";

let addr = Bytes.fromHexString("0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8");

export function handleBlocks(blocks: Block[]): Bytes {
  let acct: Account = blocks[0].account(addr);
  return Bytes.fromHexString("1");
}
```
5. run command `npm run compile && npm run setup && npm run prove -- 18882868 01 --prove`

And follow error message will be throw.
<img width="637" alt="image" src="https://github.com/hyperoracle/zkgraph-cli/assets/103174898/acdbaebd-8a7a-4e9b-b62a-6589d24fb4bc">
