### ISSUE TITLE
过长的bytes无法toHexString

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-cli#39]
当Bytes过大时，toHexString函数无法execute

### Env
- zkgraph-lib: v1.0.1
- zlhraph-cli: v1.0.0

### Reproduce
1. `npm init zkgraph@latest`
2. Follow the guide to initialize a project of type "event"
3. modify src/mapping.ts as follow:
```typescript
//@ts-ignore
import { Bytes, Block } from "@hyperoracle/zkgraph-lib";

export function handleBlocks(blocks: Block[]): Bytes {
  const event = blocks[0].events[0];
  event.data.toHexString();
  return Bytes.empty();
}
```

4. modify src/zkgraph.yaml as follow:
```yaml
specVersion: 0.0.2
apiVersion: 0.0.2
name: eg_event
description: "This demo zkGraph shows 3 ways to access / filter out source events."
repository: https://github.com/hyperoracle/zkgraph
dataSources:
  - kind: ethereum
    network: sepolia
    event:
      - address: '0xfa002dc692d045afde265d5eac09d012c1af50e8'
        events: 
          - "ethscriptions_protocol_CreateEthscription(address,string)"

mapping:
  language: wasm/assemblyscript
  file: ./mapping.ts
  handler: handleBlocks

dataDestinations:
  - kind: ethereum
    network: sepolia
    address: "0x0000000000000000000000000000000000000001"
```

5. `npm run compile && npm run exec -- 4940316`
Next, there will be the following error message from execue.
<img width="1132" alt="image" src="https://github.com/hyperoracle/zkgraph-cli/assets/103174898/42520925-adba-40fd-9be9-776135f2a52c">
